import {SCREENS} from '../interface/screens/constant';

export const Screens: SCREENS = {
  landing: 'landing',
  signup: 'signup',
  signin: 'signin',
  home: 'home',
  card: 'card',
  statistics: 'statistics',
  settings: 'Settings',
  tab: 'tab',
  edit: 'edit',
  newcard: 'newcard',
  all: 'allcard',
  history: 'history',
  search: 'search',
  send: 'send',
  receive: 'receive',
  termsandcondition: 'termsandcondition',
  profile: 'My Profile',
  languauge: 'Language',
  change: 'Change Password',
  contactus: 'Contact Us',
  privacy: 'Privacy Policy',
  biometric: 'Biometric',
  transactions: 'transactions',
};
